language: rust
rust:
  - stable 
  - nightly
os:
  - osx
  - linux
env:
  - FEATURES=""
  - FEATURES="exception"
matrix:
  exclude:
    - os: linux
      env: FEATURES="exception"
sudo: false
before_script: if [ "$TRAVIS_OS_NAME" = "linux" ]; then export FEATURES="gnustep $FEATURES"; fi
script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"
addons:
  apt:
    packages:
      - gnustep-devel
